apiVersion: v1
kind: Deployment
metadata:
  name: asset-management-ui
  labels:
    app: asset-management-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asset-management-ui
  template:
    metadata:
      labels:
        app: asset-management-ui
    spec:
      containers:
      - name: asset-management-ui
        image: ghcr.io/abhirambsn/asset-management-ui:latest
        ports:
        - containerPort: 80